-- Scripts ddl para o ambiente operacional

use dw_ocorrencias_hospitalares

DROP TABLE IF EXISTS TB_OCORRENCIA
DROP TABLE IF EXISTS TB_HOSPITAL
DROP TABLE IF EXISTS TB_DOENCA
DROP TABLE IF EXISTS TB_OCORRECIA_DOENCA
DROP TABLE IF EXISTS TB_MEDICO
DROP TABLE IF EXISTS TB_PACIENTE

CREATE TABLE TB_OCORRENCIA(
COD_OCORRENCIA INT NOT NULL PRIMARY KEY,
DT_DATA DATETIME NOT NULL,
CRM INT NOT NULL,
CNPJ INT NOT NULL,
COD_SUS INT NOT NULL
CONSTRAINT FK_MEDICO FOREIGN KEY (COD_MEDICO) REFERENCES TB_MEDICO (COD_MEDICO),
CONSTRAINT FK_PACIENTE FOREIGN KEY (COD_SUS) REFERENCES TB_PACIENTE (COD_SUS),
CONSTRAINT FK_HOSPITAL FOREIGN KEY (CNPJ) REFERENCES TB_HOSPITAL (CNPJ),
)

INSERT INTO TB_OCORRENCIA(COD_OCORRENCIA, DT_DATA, CRM, CNPJ, COD_SUS)
VALUES(1, GETDATE(), 123,123, 1)
INSERT INTO TB_OCORRENCIA(COD_OCORRENCIA, DT_DATA, CRM, CNPJ, COD_SUS)
VALUES(2, GETDATE(), 124,124, 2)

CREATE TABLE TB_HOSPITAL(
CNPJ INT NOT NULL PRIMARY KEY, -- O CNPJ está assumindo o papel de CÓDIGO DO HOSPITAL
NOME  VARCHAR(100) NOT NULL,
RUA VARCHAR(100) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
UF VARCHAR(2) NOT NULL
)

INSERT INTO TB_HOSPITAL (CNPJ, NOME, RUA, BAIRRO, CIDADE, UF)
VALUES(1,'SANTA CASA', 'TUIUTI', 'JABOATAO DOS GUARARAPES', 'SAO PAULO', 'SP')
INSERT INTO TB_HOSPITAL (CNPJ, NOME, RUA, BAIRRO, CIDADE, UF)
VALUES(2,'SANTA MONICA', 'BRAS', 'LIBERDADE', 'SAO PAULO', 'SP')

CREATE TABLE TB_PACIENTE(
COD_SUS INT NOT NULL PRIMARY KEY,
NOME  VARCHAR(100) NOT NULL,
CPF VARCHAR(15) NOT NULL,
IDADE INT NOT NULL,
RUA VARCHAR(100) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
UF VARCHAR(2) NOT NULL,
SEXO VARCHAR(1) NOT NULL
)


INSERT INTO TB_PACIENTE (CD_SUS, NOME,CPF,IDADE, RUA, BAIRRO, CIDADE, UF, SEXO)
VALUES(1,'MONICA', '123123123', 20, 'AGROVILA', 'CENTRO', 'MOITA BONITA', 'SE', 'F')

CREATE TABLE TB_MEDICO(
COD_MEDICO INT NOT NULL PRIMARY KEY,
CRM INT NOT NULL,
NOME VARCHAR(50) NOT NULL
)

INSERT INTO TB_MEDICO (COD_MEDICO, CRM, NOME) VALUES (1, 1, 'ANDRE')
INSERT INTO TB_MEDICO (COD_MEDICO, CRM, NOME) VALUES (2, 2, 'ANDREA')

CREATE TABLE TB_DOENCA(
COD_DOENCA INT NOT NULL PRIMARY KEY,
NOME VARCHAR NOT NULL
)
INSERT INTO TB_DOENTB_DOENCA(COD_DOENCA, NOME) VALUES (1, 'COVID')
INSERT INTO TB_DOENTB_DOENCA(COD_DOENCA, NOME) VALUES (2, 'RESFRIADO')

CREATE TABLE OCORRENCIA_DOENCA(
COD_OCORRENCIA INT NOT NULL PRIMARY KEY,
COD_DOENCA INT NOT NULL PRIMARY KEY
CONSTRAINT FK_OCORRENCIA FOREIGN KEY (COD_OCORRENCIA) REFERENCES TB_OCORRENCIA (COD_OCORRENCIA),
CONSTRAINT FK_DOENCA FOREIGN KEY (COD_DOENCA) REFERENCES TB_DOENCA (COD_DOENCA)

)

-- FALTA SÓ O INDEX



     


