-- Scripts ddl para o ambiente operacional

use dw_ocorrencias_hospitalares

DROP TABLE IF EXISTS TB_OCORRENCIA
DROP TABLE IF EXISTS TB_HOSPITAL
DROP TABLE IF EXISTS TB_DOENCA
DROP TABLE IF EXISTS TB_MEDICO
DROP TABLE IF EXISTS TB_PACIENTE

CREATE TABLE TB_OCORRENCIA(
COD_OCORRENCIA INT NOT NULL PRIMARY KEY,
DT_DATA DATETIME NOT NULL,
COD_MEDICO INT NOT NULL,
CNPJ INT NOT NULL,
COD_SUS INT NOT NULL,
COD_DOENCA INT NOT NULL
CONSTRAINT FK_MEDICO FOREIGN KEY (COD_MEDICO) REFERENCES TB_MEDICO (COD_MEDICO),
CONSTRAINT FK_PACIENTE FOREIGN KEY (COD_SUS) REFERENCES TB_PACIENTE (COD_SUS),
CONSTRAINT FK_HOSPITAL FOREIGN KEY (CNPJ) REFERENCES TB_HOSPITAL (CNPJ),
CONSTRAINT FK_DOENCA FOREIGN KEY (COD_DOENCA) REFERENCES TB_DOENCA(COD_DOENCA),
)

CREATE TABLE TB_HOSPITAL(
CNPJ INT NOT NULL PRIMARY KEY, -- O CNPJ está assumindo o papel de CÓDIGO DO HOSPITAL
NOME  VARCHAR(100) NOT NULL,
RUA VARCHAR(100) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
UF VARCHAR(2) NOT NULL
)

CREATE TABLE TB_PACIENTE(
COD_SUS INT NOT NULL PRIMARY KEY, -- O código do SUS corresponde ao CÓDIGO DO PACIENTE
NOME  VARCHAR(100) NOT NULL,
CPF VARCHAR(15) NOT NULL,
RUA VARCHAR(100) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
UF VARCHAR(2) NOT NULL,
SEXO VARCHAR(1) NOT NULL
)

CREATE TABLE TB_MEDICO(
COD_MEDICO INT NOT NULL PRIMARY KEY,
CRM INT NOT NULL,
NOME VARCHAR(50) NOT NULL, 
ESPECIALIDADE VARCHAR(100) NOT NULL
)

CREATE TABLE TB_DOENCA(
COD_DOENCA INT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL
)


CREATE INDEX IX_OCORRENCIA_DOENCA ON TB_OCORRENCIA (COD_DOENCA)
CREATE INDEX IX_HOSPITAL_OCORRENCIA ON TB_OCORRENCIA (CNPJ)
CREATE INDEX IX_DATA_OCORRENCIA ON TB_OCORRENCIA(DT_DATA)
CREATE INDEX IX_OCORRENCIA_MEDICO ON TB_OCORRENCIA(COD_MEDICO)