use dw_ocorrencias_hospitalares

create or alter procedure sp_fato_ocorrencia
as
BEGIN
	declare @DATA_CARGA DATETIME, @COD_HOSPITAL int, @COD_FAIXA_ETARIA int, @COD_DOENCA int, @COD_MEDICO int, @COD_PACIENTE int, @COD_TEMPO int, @QUANTIDADE int   
	DECLARE @ID_HOSPITAL int, @ID_DOENCA int, @ID_MEDICO int, @ID_FAIXA_ETARIA int, @ID_PACIENTE int, @ID_TEMPO int 

	declare ocorrencias cursor 
	for select DATA_CARGA, COD_HOSPITAL, COD_FAIXA_ETARIA, COD_DOENCA, COD_PACIENTE, COD_MEDICO, QUANTIDADE from TB_AUX_OCORRENCIA

	open ocorrencias

	delete FATO_OCORRENCIA

	FETCH NEXT FROM ocorrencias
	INTO @DATA_CARGA, @COD_HOSPITAL, @COD_FAIXA_ETARIA, @COD_DOENCA, @COD_MEDICO, @COD_PACIENTE, @QUANTIDADE

	while(@@FETCH_STATUS = 0)
	BEGIN
		SELECT @ID_DOENCA = ID_DOENCA FROM DIM_DOENCA WHERE @COD_DOENCA = COD_DOENCA

		SELECT @ID_TEMPO = ID_TEMPO FROM DIM_TEMPO WHERE @DATA_CARGA = DATA

		SELECT @ID_HOSPITAL = ID_HOSPITAL FROM DIM_HOSPITAL WHERE @COD_HOSPITAL = COD_HOSPITAL

		SELECT @ID_PACIENTE = ID_PACIENTE FROM DIM_PACIENTE WHERE @COD_PACIENTE = COD_PACIENTE

		SELECT @ID_MEDICO = ID_MEDICO FROM DIM_MEDICO WHERE @COD_MEDICO = COD_MEDICO

		SELECT @ID_FAIXA_ETARIA = ID_FAIXA_ETARIA FROM DIM_FAIXA_ETARIA WHERE @COD_FAIXA_ETARIA = COD_FAIXA_ETARIA

		-- Colocar um if para tratar as variáveis que podem rever valores null, e caso isto ocorra todos
		-- os ids devem ser armazenados na TABELA DE VIOLAÇÃO

		INSERT INTO FATO_OCORRENCIA
		VALUES(@ID_DOENCA, @ID_TEMPO, @ID_HOSPITAL, @ID_PACIENTE, @ID_MEDICO, @ID_FAIXA_ETARIA, @QUANTIDADE)
	END


	CLOSE OCORRENCIAS
	DEALLOCATE OCORRENCIAS
END