use dw_ocorrencias_hospitalares

create or alter procedure sp_fato_ocorrencia(@DATA_CARGA datetime)
as
BEGIN
	DECLARE @COD_HOSPITAL int, @COD_FAIXA_ETARIA int, @COD_DOENCA int, @COD_MEDICO int, @COD_PACIENTE int, @COD_TEMPO int, @QUANTIDADE int,  @ID_HOSPITAL int,
	@ID_DOENCA int, @ID_MEDICO int, @ID_FAIXA_ETARIA int, @ID_PACIENTE int, @ID_TEMPO int, @mensagemDeErro varchar(50)

	declare ocorrencias cursor 
	for select COD_HOSPITAL, COD_FAIXA_ETARIA, COD_DOENCA, COD_PACIENTE, COD_MEDICO, QUANTIDADE from TB_AUX_OCORRENCIA
	where DATA_CARGA = @DATA_CARGA

	open ocorrencias

	delete FATO_OCORRENCIA

	FETCH NEXT FROM ocorrencias
	INTO @COD_HOSPITAL, @COD_FAIXA_ETARIA, @COD_DOENCA, @COD_MEDICO, @COD_PACIENTE, @QUANTIDADE

	while(@@FETCH_STATUS = 0)
	BEGIN
		SET @mensagemDeErro = NULL

		SET @ID_DOENCA = (SELECT  ID_DOENCA FROM DIM_DOENCA WHERE @COD_DOENCA = COD_DOENCA)
		IF(@ID_DOENCA IS NULL)
		BEGIN
			set @mensagemDeErro = 'ID_DOENCA não encontrado!!'
		END

		SET @ID_TEMPO = (SELECT  ID_TEMPO FROM DIM_TEMPO WHERE @DATA_CARGA = DATA)
		IF(@ID_TEMPO IS NULL)
		BEGIN
			set @mensagemDeErro = 'ID_TEMPO não encontrado!!'
		END

		SET @ID_HOSPITAL = (SELECT ID_HOSPITAL FROM DIM_HOSPITAL WHERE @COD_HOSPITAL = COD_HOSPITAL)
		IF(@ID_HOSPITAL IS NULL)
		BEGIN
			set @mensagemDeErro = 'ID_HOSPITAL não encontrado!!'
		END

		SET @ID_PACIENTE = (SELECT ID_PACIENTE FROM DIM_PACIENTE WHERE @COD_PACIENTE = COD_PACIENTE)
		IF(@ID_PACIENTE IS NULL)
		BEGIN
			set @mensagemDeErro = 'ID_PACIENTE não encontrado!!'
		END

		SET @ID_MEDICO = (SELECT ID_MEDICO FROM DIM_MEDICO WHERE @COD_MEDICO = COD_MEDICO)
		IF(@ID_MEDICO IS NULL)
		BEGIN
			set @mensagemDeErro = 'ID_MEDICO não encontrado!!'
		END

		SET @ID_FAIXA_ETARIA = (SELECT ID_FAIXA_ETARIA FROM DIM_FAIXA_ETARIA WHERE @COD_FAIXA_ETARIA = COD_FAIXA_ETARIA)
		IF(@ID_FAIXA_ETARIA IS NULL)
		BEGIN
			set @mensagemDeErro = 'ID_FAIXA_ETARIA não encontrado!!'
		END

		-- Colocar um if para tratar as variáveis que podem rever valores null, e caso isto ocorra todos
		-- os ids devem ser armazenados na TABELA DE VIOLAÇÃO
		IF(@mensagemDeErro is null)
		BEGIN
			INSERT INTO FATO_OCORRENCIA
			VALUES(@ID_DOENCA, @ID_TEMPO, @ID_HOSPITAL, @ID_PACIENTE, @ID_MEDICO, @ID_FAIXA_ETARIA, @QUANTIDADE)
		END
		ELSE
		BEGIN
			INSERT INTO TB_VIOLACAO_OCORRENCIA
			VALUES(@DATA_CARGA, @COD_HOSPITAL, @COD_FAIXA_ETARIA, @COD_DOENCA, @COD_PACIENTE, @COD_MEDICO, @QUANTIDADE, @mensagemDeErro, GETDATE())
		END

		FETCH NEXT FROM ocorrencias
		INTO @COD_HOSPITAL, @COD_FAIXA_ETARIA, @COD_DOENCA, @COD_MEDICO, @COD_PACIENTE, @QUANTIDADE
	END

	CLOSE OCORRENCIAS
	DEALLOCATE OCORRENCIAS
END